sudo: required
services:
  - docker

before_install:
  - docker build -t fengchen/ci-test-repo -f Dockerfile.dev .
  
script:
  - docker run fengchen/ci-test-repo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-652613104016"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"